baseURL = "http://goodfeels.net/"
languageCode = "en-us"
title = "Good Feels"
theme = "goodfeels-theme"
sectionPagesMenu = "main"                                               
googleAnalytics = "UA-102910248-1"

[params]
    description = "Hacking Self Improvement"
    headerPic = "/img/bg-img.svg"
