baseURL = "http://goodfeels.net/"
languageCode = "en-us"
title = "Good Feels"
theme = "goodfeels-theme"
sectionPagesMenu = "main"                                               

[params]
    description = "Hacking Self Improvement"
